### ISSUE TITLE
Create chimayo.github.io website

### ISSUE THREAD

**Issue by stevehorsfield** [chimayo/chimayo#1]
Create an initial structure to support documentation, blogging, news and links.

**Comment by ForNeVeR** [comment]
Your project is extremely interesting, and I see that the documentation site is evolving. Could you please add a simplest usage example as a next step?

I am very concerned about development of SSIS packages with F#, but still cannot get the proposed usage of Chimayo (and I've already grokked the source a bit).

**Comment by stevehorsfield** [comment]
@ForNeVeR: absolutely my intention. Struggling to get enough time with work and home commitments, but these things are definitely coming. Glad I've piqued your interest!

**Comment by stevehorsfield** [comment]
@ForNeVeR: this might help you get started:

I see there's some issue with the NuGet packages. The binaries are only linked for .NET 4.6, apologies for that. I've not worked a lot with creating NuGet packages so this is something for me to work on...

Create a new .NET 4.6 F# console app. I'm using VS 2015 community edition.

``` fsharp
open Chimayo.Ssis.Ast.ControlFlow
open Chimayo.Ssis.Ast.ControlFlowApi
open Chimayo.Ssis.Writer2012

let pkg = 
    Package.create @"My package"
    |> Package.addVariables
        [
            Variables.createSimple @"User::myVar" 10
            Variables.createSimple @"User::myVar2" "String variable"
            Variables.create "CustomNamespace" "exprVar" false false "" (Some """ "a" + "b" """)
        ]
    |> Package.addConnectionManagers
        [
            OleDbConnectionManager.create "SQL"
                <| SqlConnectionStringHelper.createInlineOleDbConnectionString "." "tempdb" None "Chimayo SSIS Example"
        ]
    |> Package.addExecutables
        [
            let exes =
                [
                    ExecuteSql.createSimple "SQL1" "SQL" "PRINT 'HELLO'"
                    ExecuteSql.createSimple "SQL2" "SQL" "PRINT 'WORLD'"
                    ExecuteSql.createSimple "SQL3" "SQL" "PRINT 'FROM'"
                    ExecuteSql.createSimple "SQL4" "SQL" "PRINT 'CHIMAYO'"
                ]
            let final, priors = exes |> PrecedenceConstraints.chain CfExecutableResult.Success
            yield! priors
            yield final
        ]

[<EntryPoint>]
let main argv = 
    pkg
    |> Chimayo.Ssis.Writer2012.PackageBuilder.toString
    |> printf "%s\n" 
    System.Console.ReadLine() |>ignore
    0
```

When run, you'll get a SSIS 2012 package dump. It's showing utf-16 because we're writing to a string. If you directly write to a file (see `PackageBuilder` functions), it will write in utf-8.

If you try to execute the package, it may or may not work. First thing to check is whether the SQL Server Native Client version is available. See https://github.com/chimayo/chimayo/blob/master/src/Chimayo.Ssis.Ast/UtilitiesModule.fs#L45 if you want to adapt this.

That should get you started. You'll find data types are all in Ast.ControlFlow and Ast.DataFlow, and functions that help you create and manipulate objects are in Ast.ControlFlowApi and Ast.DataFlowApi. They are really the core of the system.

Feel free to ask questions here or on Twitter to `@ChimayoProject` or `@s_horsfield`

**Comment by stevehorsfield** [comment]
There's also a lot of scope for improving the API. Feel free to create issues if you have suggestions or comments on things that don't work well.

**Comment by stevehorsfield** [comment]
@ForNeVeR: see https://chimayo.github.io/chimayo/gettingstarted.html

**Comment by ForNeVeR** [comment]
Thank you!
